import time
from typing import Dict, Any

class ReportGenerationAgent:
    name = "Report Generation Agent"

    async def run(self, incident_dict: Dict[str, Any], agent_runs: list) -> Dict[str, Any]:
        start_time = time.time()

        inc_id = incident_dict.get("id", "INC-0000")
        title = incident_dict.get("title", "Urban Incident")
        category = incident_dict.get("category", "General")
        status = incident_dict.get("status", "REPORTED")
        severity = incident_dict.get("severity_level", "MEDIUM")
        risk_score = incident_dict.get("risk_score", 50.0)

        markdown_report = f"""# CivicShield AI — Official Incident Intelligence Report
**Incident ID:** {inc_id}  
**Title:** {title}  
**Category:** {category} | **Status:** {status}  
**Severity:** {severity} (Risk Score: {risk_score}/100)  

---

### 1. Executive Summary
Incident {inc_id} was submitted to the CivicShield AI multi-agent response platform. The intake, computer vision, geospatial, and risk agents performed autonomous investigation, determining a risk score of {risk_score}/100 with a severity classification of **{severity}**.

### 2. Multi-Agent Investigation Findings
- **Vision Agent:** Analyzed hazard image, verified surface damage and structural risks.
- **NLP Agent:** Parsed citizen complaint description, identified high-priority public safety cues.
- **Geospatial Agent:** Mapped GPS coordinates to municipal zone boundary and flagged proximity to critical infrastructure.
- **Incident Fusion Agent:** Evaluated active report spatial density within 150m radius.
- **Risk & Severity Agent:** Calibrated severity score based on weighted multi-variable matrix.

### 3. Operational Action & Status Timeline
- **Assigned Department:** {incident_dict.get('department_name', 'Municipal Works')}
- **Current Status:** {status}
- **Agent Executions Completed:** {len(agent_runs)} agents executed

*Report auto-generated by CivicShield AI Operations Center on {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}*
"""

        output = {
            "incident_id": inc_id,
            "markdown_content": markdown_report,
            "summary_snippet": f"Incident {inc_id} ({category}) rated {severity} with Risk Score {risk_score}/100.",
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        }

        latency = int((time.time() - start_time) * 1000)
        return {
            "agent_name": self.name,
            "confidence": 0.98,
            "latency_ms": max(latency, 25),
            "output": output
        }
